### PR TITLE
Laravel 5.3 SMS Notifications Channel

### PR DESCRIPTION
**Pull request by kduma**
And here is my second PR: The Laravel Notifications Driver

Probably need some tests.

### CODE REVIEW

**Comment by SimplyCorey** [comment]
@kduma This looks like a great pull request and feature.  Anyway you can write the tests?

**Comment by kduma** [comment]
I have no time until January to do that.

Also from what I saw in other packages, other notifications channels packages tests api calls which are driver specific.

**Comment by SimplyCorey** [comment]
That is fine, maybe I'll be able to beat you to it.  I am very busy as well!

**Comment by kduma** [comment]
Better late than never: **Tests written!** 😃 

One drawback it that, to run the test you need to `composer require illuminate/notifications`. I've didn't want to include it in `composer.json` file to preserve compatibility with Laravel 5.2 and older.

**Pull request closed without merging**
